spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/fostertogether
spring.datasource.username=fostertogether
spring.datasource.password=fostertogether
# CORS allowed origins
ftmn.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_twZRjZ9VP